name: nuget
on:
  push:
    paths:
      - src/**
      - test/**
      - Okkema.sln
      - .github/workflows/nuget.yaml
concurrency: nuget
jobs:
  nuget:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Build, test, and publish packages
        uses: okkema/actions/dotnet-publish@v2
        with:
          nuget-token: ${{ secrets.GITHUB_TOKEN }}
